//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class options
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> product_code { get; set; }
        public string status { get; set; }
    
        public virtual products products { get; set; }
    }
}
