//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public products()
        {
            this.options = new HashSet<options>();
        }
    
        public int code { get; set; }
        public string nombre { get; set; }
        public Nullable<int> stock { get; set; }
        public string estado { get; set; }
        public string proveedor { get; set; }
        public byte[] img { get; set; }
    
        public virtual ICollection<options> options { get; set; }
        public string ImageLocation { get; internal set; }
    }
}
